### ISSUE TITLE
centos npm start 报错

### ISSUE THREAD

**Issue by fydy** [zhuzhuyule/HexoEditor#38]
> HexoEditor@1.5.30 start /home/centos/fydy.github.io/HexoEditor
> electron .

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! HexoEditor@1.5.30 start: `electron .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the HexoEditor@1.5.30 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by zmkoo000** [comment]
same problem when I execute `npm start`
```
HexoEditor@1.5.30 start /opt/HexoEditor
> electron .


npm ERR! Linux 3.10.0-327.36.3.el7.x86_64
npm ERR! argv "/usr/local/nodejs/bin/node" "/bin/npm" "start"
npm ERR! node v6.8.0
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! HexoEditor@1.5.30 start: `electron .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the HexoEditor@1.5.30 start script 'electron .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the HexoEditor package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs HexoEditor
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls HexoEditor
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/HexoEditor/npm-debug.log
```

**Comment by zmkoo000** [comment]
Here's the log:
``` bash
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/nodejs/bin/node', '/bin/npm', 'start' ]
2 info using npm@3.10.8
3 info using node@v6.8.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle HexoEditor@1.5.30~prestart: HexoEditor@1.5.30
6 silly lifecycle HexoEditor@1.5.30~prestart: no script for prestart, continuing
7 info lifecycle HexoEditor@1.5.30~start: HexoEditor@1.5.30
8 verbose lifecycle HexoEditor@1.5.30~start: unsafe-perm in lifecycle true
9 verbose lifecycle HexoEditor@1.5.30~start: PATH: /usr/local/nodejs/lib/node_modules/npm/bin/node-gyp-bin:/opt/HexoEditor/node_modules/.bin:/usr/local/nodejs/bin:/sbin:
/bin:/usr/sbin:/usr/bin
10 verbose lifecycle HexoEditor@1.5.30~start: CWD: /opt/HexoEditor
11 silly lifecycle HexoEditor@1.5.30~start: Args: [ '-c', 'electron .' ]
12 silly lifecycle HexoEditor@1.5.30~start: Returned: code: 1  signal: null
13 info lifecycle HexoEditor@1.5.30~start: Failed to exec start script
14 verbose stack Error: HexoEditor@1.5.30 start: `electron .`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/nodejs/lib/node_modules/npm/lib/utils/lifecycle.js:255:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/nodejs/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid HexoEditor@1.5.30
16 verbose cwd /opt/HexoEditor
17 error Linux 3.10.0-327.36.3.el7.x86_64
18 error argv "/usr/local/nodejs/bin/node" "/bin/npm" "start"
19 error node v6.8.0
20 error npm  v3.10.8
21 error code ELIFECYCLE
22 error HexoEditor@1.5.30 start: `electron .`
22 error Exit status 1
23 error Failed at the HexoEditor@1.5.30 start script 'electron .'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the HexoEditor package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     electron .
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs HexoEditor
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls HexoEditor
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by fydy** [comment]
@zhuzhuyule npm start ，These errors have occurred。

**Comment by Johnsonzcode** [comment]
@zhuzhuyule same question, same info, and same log.
More detial:
I am using linuxdeploy(arm64, ubuntu18.04, android 6.0), but many xxx.so.x have been installed as long as it needs.

It seems electron can't start: ```electron .```
