### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by zzydy** [zhuzhuyule/HexoEditor#79]
Uncaught Exception:
TypeError: Cannot read property 'debug' of undefined
    at new MoeditorWindow (/Applications/HexoEditor.app/Contents/Resources/app.asar/app/moe-window.js:46:35)
    at MoeditorApplication.open (/Applications/HexoEditor.app/Contents/Resources/app.asar/app/moe-app.js:63:31)
    at App.app.on (/Applications/HexoEditor.app/Contents/Resources/app.asar/app/index.js:51:16)
    at emitTwo (events.js:125:13)
    at App.emit (events.js:213:7)

给小白支个招吧。。。。

**Comment by zzydy** [comment]
系统是macOS 10.14 。。。

**Comment by tabris-trees** [comment]
我是ubuntu的系统也有这个问题，图片也上传不了，太难了
